server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  #   Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:real_coding
    username: cnu
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p %F %c %m"
  level:
    com.cnu.com.cnu.devlog_springboot: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'

slack:
  webhook:
    url: 'https://hooks.slack.com/services/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'

logging.level:
  org.hibernate.SQL: debug