spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  #   Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:real_coding
    username: cnu
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

logging.level:
  org.hibernate.SQL: debug